version: '3.8'

services:
  chat-service:
      build: .
      container_name: chatservice_app
      volumes:
        - .:/go/src
      ports:
        - "8080:8080"
        - "50052:50051"

  mysql:
    image: mysql:8
    container_name: chatservice_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=chat
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql